### PR TITLE
Just merging jenkinsci/slack-plugin:master

### PR DESCRIPTION
**Pull request by roni-frantchi**
@fstehle thanks a lot for [your PR](https://github.com/jenkinsci/slack-plugin/pull/178).
Really needed that, and looks like it takes the guys awhile to review and approve your PR, so I forked, merged and resolved conflicts from [jenkinsci/slack-plugin:master](https://github.com/jenkinsci/slack-plugin) for our own usage.
Just thought you may wanna merge it in and appeal for another review.

### CODE REVIEW

**Comment by samrocketman** [comment]
Hey Roni, it's not that the project takes a while to review changes.  It mostly hasn't had any active maintainers for quite a while.  I've mostly backed away but saw the amount of outstanding PRs on the project and decided to start merging them again.  Do you mind assisting again resolving the conflicts in https://github.com/jenkinsci/slack-plugin/pull/178?

**Comment by roni-frantchi** [comment]
@samrocketman terribly sorry I had missed this one somehow...
Noticed others have pitched in though. I'll keep my eyes open and try to help out more next time

**Comment by samrocketman** [comment]
No worries :-)

**Comment by PirminTapken** [comment]
Hey @roni-frantchi I will close this as this is stale for half a year now, and we put our effort in the original PR and are still waiting for something to happen.

**Pull request closed without merging**
